version: 2
project_name: dck-wings

builds:
  - binary: dck-wings
    goos: [linux]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}

nfpms:
  - package_name: dck-wings
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
    formats: [deb]
    vendor: kuranix
    homepage: https://github.com/kuranix/dck-wings
    description: dck agent for container nodes

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats: [tar.gz]
    files:
      - LICENSE*

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

release:
  github:
    owner: kuranix
    name: dck-wings
